import React from 'react'
import Layout from '../components/Layout'

const About = () => {
  return (
    <div>
        <Layout>
        <h1>About Page</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perferendis dolores quas dignissimos nisi, ullam fuga aperiam pariatur quasi. Reprehenderit, sed?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ut non ipsam placeat cupiditate saepe eveniet, sint laborum. Maxime, eos exercitationem fugiat ipsam officiis ipsa quidem ullam aspernatur minus necessitatibus sunt alias nostrum, modi, quam magnam. Esse placeat vel eius quidem corrupti, numquam est cum sunt iure, harum accusantium cupiditate blanditiis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum vitae dolorem corporis ullam, nobis rem sapiente. Rem sit nisi laboriosam quod? Velit amet assumenda est corrupti dicta earum, suscipit quod. Hic unde nisi at expedita harum, illo eum ipsum, optio cupiditate voluptatibus cum dignissimos et deleniti laborum ad laudantium neque aliquid? Voluptas minus voluptates nam dolores, alias libero sunt, eaque ullam nostrum modi unde. Doloremque voluptatem eaque impedit commodi dicta ad excepturi, quam fuga. Cum et doloribus dignissimos alias, magnam rem eveniet cumque neque ullam esse officiis ea nihil recusandae repellat commodi, harum molestias maiores explicabo. Possimus, delectus repellendus quos perferendis explicabo velit quasi libero in nemo sint exercitationem dignissimos. Sunt corporis quae non doloribus esse voluptatem enim suscipit labore modi, provident consequatur quam, optio minus quidem aliquam incidunt dolore ipsum error hic odio laborum consequuntur sapiente beatae? Ex, error quae enim eos dolores laudantium? Consectetur odio corporis voluptates placeat. Perspiciatis sunt eaque esse molestias corrupti quae veniam laboriosam saepe blanditiis consequatur? A doloribus minima eligendi illum? Eveniet optio vitae ad ipsa accusantium quia repellendus non molestiae delectus perferendis, voluptates corporis ex corrupti quae nulla, dolorem in illum quasi sequi velit! Fugit dignissimos inventore neque voluptate eum ipsa numquam nihil deleniti deserunt quidem officia atque, explicabo vel adipisci quae doloremque totam libero accusantium saepe expedita! Ducimus, beatae deserunt corrupti quas recusandae aperiam obcaecati vitae fuga libero vero nobis, qui, dolorum minima. At sit numquam consequuntur laboriosam. Harum dolorem illum porro unde qui voluptate eius, neque consequuntur minima quia atque quisquam quam! Necessitatibus at eligendi vel quia possimus. Reiciendis iusto vitae corporis deserunt maxime vero dicta id quam! At temporibus impedit debitis illum asperiores? Doloribus, expedita tempore sit iusto illo voluptas dignissimos corporis dolorem nobis nemo in recusandae debitis quasi cumque dolor laboriosam. Iure optio quod unde cumque accusamus tenetur, eveniet dignissimos quae. Beatae praesentium voluptatem libero consequuntur. Corporis doloribus id, quibusdam ex aperiam quae temporibus odit culpa accusantium hic ipsa distinctio quis cumque possimus doloremque obcaecati nesciunt quas aliquam? Voluptatum velit cumque praesentium, tenetur aut blanditiis facilis laborum quia nisi natus odio sapiente repudiandae necessitatibus libero vitae minus! Labore aliquam sit, commodi eveniet enim veritatis impedit suscipit dolores totam, magnam velit accusamus non eum quis ducimus nam, provident ratione vitae animi temporibus ut! Quas aliquid corporis nulla laudantium, veritatis consectetur possimus modi optio. Iste placeat cum maxime eos asperiores. Commodi vero delectus neque rerum id expedita sunt odio quas! Laborum.</p>
        </Layout>
    </div>
  )
}

export default About